repos:
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.29.0
    hooks:
    -   id: pyupgrade
        args: [--py37-plus]
# -   repo: https://github.com/psf/black
#     rev: 21.9b0
#     hooks:
#     -   id: black
# -   repo: https://github.com/PyCQA/isort
#     rev: 5.10.1
#     hooks:
#     -   id: isort
# -   repo: local
#     hooks:
#       - id: actionlint
#         name: actionlint
#         entry: actionlint
#         args: [-ignore, 'property ".+" is not defined in object type']
#         language: script
#         types: ["yaml"]
#         files: ^.github/workflows/
